Refactor repositories role to use variables to configure repos
AFCYBER-DREAM/repos pull request #6
Opened 2019-05-06 18:44 UTC by leader716

2019-05-08 13:45 UTC, ragingpastry requested changes

2019-05-08 13:45 UTC, ragingpastry commented on molecule/default/playbook.yml
> +    - repos:
I believe this should be `repositories` instead of `repos`

2019-05-08 13:45 UTC, ragingpastry commented on molecule/default/playbook.yml
> +          - { url: "https://centos7.iuscommunity.org" }
This doesn't appear to work on centos. Running `molecule converge` fails and logging into the container manually will result in the same error "No package https://centos7.iuscommunity.org available."

2019-05-08 13:45 UTC, ragingpastry commented on molecule/default/tests/test_default.py
> +    assert f.group == 'root'
Can we add some simple testinfra tests? Ensuring that we can download/install a package provided by one of the configured repos should do the trick

2019-05-08 13:45 UTC, ragingpastry commented on meta/main.yml
>    min_ansible_version: 2.0
We should probably bump this up at some point or test against all ansible versions between this and latest. This should be included in this PR, more just making note for later

2019-05-08 13:56 UTC, jpward1981 commented on molecule/default/playbook.yml
> +    - repos:
You are correct, I have updated this in the latest PR

2019-05-09 02:05 UTC, ragingpastry requested changes
Squash up some of these commits and we should be good to go!

2019-05-09 17:02 UTC, ragingpastry approved these changes

2019-05-09 17:02 UTC, merged