Add the option to disable certificate verification
AFCYBER-DREAM/repos pull request #7
Opened 2019-05-15 19:35 UTC by leader716

When attemting to run this role in an airgapped network in a docker
container, not all of the certificates will validate. This adds the
options to set a flag in the dictionary to disable this verification.
By default verification is still enabled.

2019-05-15 19:40 UTC, ragingpastry requested changes
We should set this new value in defaults/main.yml. Its blank right now but we should also go back and do another PR and set default values for things

2019-05-15 22:35 UTC, leader716 commented
@ragingpastry I was thinking on this more this afternoon, the reason why we don't have any defaults defined is there isn't a default for this role unless we could determine a set of repos that need to be added to all hosts depending on their distribution. The way that this role is designed to work is any rep that needs to be added/modified will be passed in via a dictionary.

2019-05-16 12:29 UTC, ragingpastry commented
Makes sense. Let's do it!

2019-05-16 12:29 UTC, ragingpastry approved these changes

2019-05-16 12:29 UTC, merged